config/routes.rb
HmsNotifier::Application.routes.draw do
  namespace :admin do
    get '/' => :index
    resources :enrollments
    resources :users, :only => [:index, :show]

    resources :message_streams, :path => :streams, :only => [:index, :show] do
      resources :messages, :only => [:index, :show]
    end

    resources :notifications, :only => [:index, :show] do
      resources :notification_updates, :path => :updates, :only => [:index, :show]
      resources :notification_responses, :path => :responses, :only => [:index, :show]
    end
  end

end

app/models/notification.rb
class Notification < ActiveRecord::Base
  belongs_to :enrollment
  belongs_to :message
  has_many :updates, :class_name => 'NotificationUpdate'
  has_many :responses, :class_name => 'NotificationResponse'

  after_initialize :default_values
  before_validation :prevent_reactivation
  before_save :generate_uuid, :unless => :uuid?

  NEW = 'NEW'
  TEMP_FAIL = 'TEMP_FAIL'
  PERM_FAIL = 'PERM_FAIL'
  DELIVERED = 'DELIVERED'
  CANCELLED = 'CANCELLED'
  ACTIVE_STATUSES = [ NEW, TEMP_FAIL ]
  INACTIVE_STATUSES = [ PERM_FAIL, DELIVERED, CANCELLED ]
  VALID_STATUSES = [ ACTIVE_STATUSES, INACTIVE_STATUSES ].flatten

  serialize :variables, Hash

  validates :uuid, :uniqueness => true
  validates :enrollment_id, :presence => true
  validates :message_id, :presence => true, :uniqueness => { :scope => :enrollment_id }
  validates :delivery_date, :presence => true
  validates :status, :inclusion => VALID_STATUSES

  scope :active, where(:status => ACTIVE_STATUSES)

  def default_values
    self.status ||= NEW
  end

  def delivery_date
    self[:delivery_date] ||= calc_delivery_date
  end

  def active?
    ACTIVE_STATUSES.include?(status)
  end

  def cancelled?
    status == CANCELLED
  end

  def variables
    self[:variables] || {}
  end


  protected

  def calc_delivery_date
    self[:delivery_date] = nil
    if enrollment && message
      self[:delivery_date] = enrollment.stream_start + message.offset_days
    end
  end

  def generate_uuid
    write_attribute :uuid, SecureRandom.uuid
  end

  def prevent_reactivation
    return true unless changes[:status]

    before, after = changes[:status]
    if INACTIVE_STATUSES.include?(before) && ACTIVE_STATUSES.include?(after)
      # attempting to reactivate an inactive notification
      errors.add(:status, 'cannot change from inactive to active')
      false
    else
      true
    end
  end

end

app/controllers/admin/notifications_controller.rb
class Admin::NotificationsController < AdminController
  respond_to :html, :json, :js

  def index
    @notifications = Notification.order('delivery_date DESC').page(params[:page])
    respond_with @notifications
  end

  def show
    @notification = Notification.find(params[:id])
    @notification_updates = @notification.updates
    @notification_responses = @notification.responses
    respond_with @notification
  end

end

app/views/admin/notifications/_notification.html.haml
%tr{:class => cycle('even', 'odd')}
  %td= notification.id
  %td= notification.enrollment_id
  %td= notification.message_id
  %td= notification.delivery_date.strftime '%Y-%m-%d'
  %td= notification.status
  %td= notification.delivered_at.try(:strftime, '%Y-%m-%d')
  %td.actions #{link_to 'View', [:admin, notification]}

app/views/admin/notifications/index.html.haml
- @nav_hierarchy = [:notifications]

%h2 Notifications

#paginator
  = paginate @notifications, :remote => true

%table.admin-table
  %thead
    %tr
      %th ID
      %th Enrollment
      %th Message
      %th Start
      %th Status
      %th Delivered At
      %th Actions
  %tbody#notifications
    = render @notifications

app/views/admin/notifications/index.js.haml
$('#notifications').html('#{escape_javascript render(@notifications)}');
$('#paginator').html('#{escape_javascript(paginate(@notifications, :remote => true).to_s)}');

app/views/admin/notifications/show.html.haml
- @nav_hierarchy = [:notifications, @notification]

%h2 View Notification
= form_for(admin_notification_path(@notification), :html => { :class => 'admin-view' }) do |f|
  %fieldset
    .field
      = f.label :id, 'ID'
      = @notification.id
    .field
      = f.label :uuid, 'UUID'
      = @notification.uuid
    .field
      = f.label :enrollment_id, 'Enrollment ID'
      = link_to @notification.enrollment_id, admin_enrollment_path(@notification.enrollment_id)
    .field
      = f.label :message_id, 'Message ID'
      = @notification.message_id
    .field
      = f.label :delivery_date, 'Delivery Date'
      = @notification.delivery_date.strftime '%b %e, %Y @ %r %Z'
    .field
      = f.label :status
      = @notification.status
    .field
      = f.label :delivered_at, 'Delivered At'
      = @notification.delivered_at.try(:strftime, '%b %e, %Y @ %r %Z')
    .field
      = f.label :date_created, 'Date Created'
      = @notification.created_at.strftime '%b %e, %Y @ %r %Z'
    .field
      = f.label :last_updated, 'Last Updated'
      = @notification.updated_at.strftime '%b %e, %Y @ %r %Z'

%h2 Updates
%table.admin-table
  %tr
    %th ID
    %th Date
    %th Action
    %th Uploaded
    %th Response
    %th Actions
  - @notification_updates.each do |update|
    %tr{:class => cycle('even', 'odd')}
      %td= update.id
      %td= update.created_at.strftime '%Y-%m-%d'
      %td= update.action
      %td= update.uploaded_at.present? ? 'Y' : ''
      %td= update.response_code
      %td.actions #{link_to 'View', admin_notification_notification_update_path(@notification, update)}

%h2 Responses
- reset_cycle
%table.admin-table
  %tr
    %th ID
    %th Date
    %th Status
    %th Error
    %th Actions
  - @notification_responses.each do |response|
    %tr{:class => cycle('even', 'odd')}
      %td= response.id
      %td= response.created_at.strftime '%Y-%m-%d'
      %td= response.status
      %td= response.error_type
      %td.actions #{link_to 'View', admin_notification_notification_response_path(@notification, response)}