config/routes.rb
HmsNotifier::Application.routes.draw do
  namespace :admin do
    get '/' => :index
    resources :enrollments
    resources :users, :only => [:index, :show]

    resources :message_streams, :path => :streams, :only => [:index, :show] do
      resources :messages, :only => [:index, :show]
    end

    resources :notifications, :only => [:index, :show] do
      resources :notification_updates, :path => :updates, :only => [:index, :show]
      resources :notification_responses, :path => :responses, :only => [:index, :show]
    end
  end

end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :message_stream
  has_many :notifications

  validates :message_stream_id, :presence => true
  validates :name, :presence => true, :uniqueness => { :scope => :message_stream_id }
  validates :title, :presence => true
  validates :offset_days, :numericality => { :only_integer => true, :greater_than_or_equal_to => 0 }

  default_scope order('offset_days')
  scope :notifiable, lambda { |offset| where('offset_days BETWEEN ? AND ?', offset - 1, offset + 5) }

  def self.find_by_path(path)
    (sname, mname) = path.to_s.split '/'

    stream_where = MessageStream.where(:name => sname)
    where(:name => mname).joins(:message_stream).merge(stream_where).first
  end

  def path
    message_stream.name + '/' + name rescue nil
  end
end

app/controllers/admin/messages_controller.rb
class Admin::MessagesController < AdminController
  respond_to :html, :json

  def index
    @message_stream = MessageStream.find(params[:message_stream_id])
    @messages = @message_stream.messages

    respond_with @messages do |format|
      format.html { redirect_to [:admin, @message_stream] }
    end
  end

  def show
    @message_stream = MessageStream.find(params[:message_stream_id])
    @message = @message_stream.messages.find(params[:id])
    respond_with @message
  end

end

app/views/admin/messages/show.html.haml
- @nav_hierarchy = [:messages, @message_stream, @message]

%h2 View Message
= form_for(admin_message_stream_messages_path(@message_stream, @message), :html => { :class => 'admin-view' }) do |f|
  %fieldset
    .field
      = f.label :id, 'ID'
      = @message.id
    .field
      = f.label :message_stream_id, 'Message Stream ID'
      = link_to @message.message_stream_id, [:admin, @message_stream]
    .field
      = f.label :name
      = @message.name
    .field
      = f.label :title
      = @message.title
    .field
      = f.label :language
      = @message.language
    .field
      = f.label :path
      = @message.path
    .field
      = f.label :offset_days, 'Offset Days'
      = @message.offset_days
    .field
      = f.label :sms_text, 'SMS Text'
      = @message.sms_text
    .field
      = f.label :date_created, 'Date Created'
      = @message.created_at.strftime '%b %e, %Y @ %r %Z'
    .field
      = f.label :last_updated, 'Last Updated'
      = @message.updated_at.strftime '%b %e, %Y @ %r %Z'