config/routes.rb
HmsNotifier::Application.routes.draw do
  namespace :admin do
    get '/' => :index
    resources :enrollments
    resources :users, :only => [:index, :show]

    resources :message_streams, :path => :streams, :only => [:index, :show] do
      resources :messages, :only => [:index, :show]
    end

    resources :notifications, :only => [:index, :show] do
      resources :notification_updates, :path => :updates, :only => [:index, :show]
      resources :notification_responses, :path => :responses, :only => [:index, :show]
    end
  end

end

app/models/enrollment.rb
class Enrollment < ActiveRecord::Base
  belongs_to :message_stream
  has_many :notifications

  after_initialize :default_values
  before_validation :prevent_duplicate_enrollments
  before_save :cancel_all_notifications, :if => :cancelled?

  ACTIVE = 'ACTIVE'
  COMPLETED = 'COMPLETED'
  CANCELLED = 'CANCELLED'
  VALID_STATUSES = [ ACTIVE, COMPLETED, CANCELLED ]

  serialize :variables, Hash

  validates :first_name, :presence => true
  validates :phone_number, :presence => true
  validates :delivery_method, :presence => true
  validates :stream_start, :presence => true
  validates :status, :inclusion => VALID_STATUSES
  validates :message_stream_id, :presence => true

  scope :active, where(:status => ACTIVE)
  scope :completed, where(:status => COMPLETED)
  scope :cancelled, where(:status => CANCELLED)

  def default_values
    self.status ||= ACTIVE
  end

  def ready_messages
    return [] unless active?
    return [] unless ['SMS', 'IVR'].include?(delivery_method)

    offset_days = (Date.today - stream_start).to_i
    possible = message_stream.messages.where(:language => language).notifiable(offset_days)
    possible = possible.where("sms_text #{delivery_method == 'SMS' ? 'IS NOT' : 'IS'} NULL")

    existing = notifications.map(&:message)
    possible - existing
  end

  def enqueue_ready_messages
    ready_messages.each { |m| notifications.create!(:message => m) }
  end

  def active?
    status == ACTIVE
  end

  def cancelled?
    status == CANCELLED
  end

  def self.supported_languages
    Message.group(:language).map(&:language).sort
  end

  def variables
    self[:variables] || {}
  end


  protected

  def prevent_duplicate_enrollments
    duplicates = Enrollment.active \
      .where(:message_stream_id => message_stream_id) \
      .where(ext_user_id ?
        { :ext_user_id => ext_user_id } :
        { :phone_number => phone_number }
      )

    # prevent matching against ourself if already in database
    duplicates = duplicates.where('id != ?', id) if id

    if duplicates.any?
      errors.add(:base, 'would create a duplicate active enrollment')
      false
    end

    true
  end

  def cancel_all_notifications
    active_notifications = notifications.active
    active_notifications.each do |notification|
      notification.update_attributes(:status => Notification::CANCELLED)
    end

    active_notifications.all?(&:cancelled?)
  end

end

app/controllers/admin/enrollments_controller.rb
class Admin::EnrollmentsController < AdminController
  respond_to :html, :json, :js

  def index
    @enrollments = Enrollment.page(params[:page])
    respond_with :admin, @enrollments
  end

  def show
    @enrollment = Enrollment.find(params[:id])
    @notifications = @enrollment.notifications
    respond_with :admin, @enrollment
  end

  def new
    @enrollment = Enrollment.new
    respond_with :admin, @enrollment
  end

  def edit
    @enrollment = Enrollment.find(params[:id])
    respond_with :admin, @enrollment
  end

  def create
    @enrollment = Enrollment.new
    @enrollment.attributes = params[:enrollment]
    @enrollment.save
    respond_with :admin, @enrollment
  end

  def update
    @enrollment = Enrollment.find(params[:id])
    @enrollment.update_attributes(params[:enrollment])
    respond_with :admin, @enrollment
  end

  def destroy
    @enrollment = Enrollment.find(params[:id])
    @enrollment.destroy
    respond_with :admin, @enrollment
  end

end

app/views/admin/enrollments/_enrollment.html.haml
%tr{:class => cycle('even', 'odd')}
  %td= enrollment.id
  %td= enrollment.message_stream_id
  %td= enrollment.phone_number
  %td= enrollment.delivery_method
  %td= enrollment.stream_start.strftime '%Y-%m-%d'
  %td= enrollment.status
  %td.actions
    #{link_to 'View', [:admin, enrollment]}
    | #{link_to 'Edit', [:edit, :admin, enrollment]}
    | #{button_to 'Remove', [:admin, enrollment], :confirm => 'Are you sure?', :method => :delete, :class => 'action-button'}

app/views/admin/enrollments/_form.html.haml
= custom_form_for [:admin, @enrollment] do |f|
  = f.base_errors
  = f.input :first_name
  = f.input :last_name
  = f.input :phone_number
  = f.input :delivery_method, :collection => ['SMS', 'IVR'], :as => :radio_buttons
  = f.input :message_stream_id, :collection => MessageStream.all.map { |s| [s.title, s.id] }
  = f.input :language, :collection => Enrollment.supported_languages, :include_blank => false
  = f.input :stream_start, :as => :date
  = f.input :preferred_time
  = f.button :submit

app/views/admin/enrollments/edit.html.haml
- @nav_hierarchy = [:enrollments, @enrollment, :edit]

%h2 Edit Enrollment
= render 'form'

app/views/admin/enrollments/index.html.haml
- @nav_hierarchy = [:enrollments]

%h2 Enrollments

#paginator
  = paginate @enrollments, :remote => true

%table.admin-table
  %thead
    %tr
      %th ID
      %th Stream
      %th Phone Number
      %th Delivery Method
      %th Stream Start
      %th Status
      %th Actions
  %tbody#enrollments
    = render @enrollments

.actions= link_to 'New Enrollment', new_admin_enrollment_path

app/views/admin/enrollments/index.js.haml
$('#enrollments').html('#{escape_javascript render(@enrollments)}');
$('#paginator').html('#{escape_javascript(paginate(@enrollments, :remote => true).to_s)}');

app/views/admin/enrollments/new.html.haml
- @nav_hierarchy = [:enrollments, :new]

%h2 New Enrollment
= render 'form'

app/views/admin/enrollments/show.html.haml
- @nav_hierarchy = [:enrollments, @enrollment]

%h2 View Enrollment
= form_for(admin_enrollment_path(@enrollment), :html => { :class => 'admin-view' }) do |f|
  %fieldset
    .field
      = f.label :id, 'ID'
      = @enrollment.id
    .field
      = f.label :message_stream_id, 'Message Stream ID'
      = link_to @enrollment.message_stream_id, admin_message_stream_path(@enrollment.message_stream_id)
    .field
      = f.label :external_user_id, 'External User ID'
      = @enrollment.ext_user_id
    .field
      = f.label :first_name, 'First Name'
      = @enrollment.first_name
    .field
      = f.label :last_name, 'Last Name'
      = @enrollment.last_name
    .field
      = f.label :phone_number, 'Phone Number'
      = @enrollment.phone_number
    .field
      = f.label :delivery_method, 'Delivery Method'
      = @enrollment.delivery_method
    .field
      = f.label :language
      = @enrollment.language
    .field
      = f.label :preferred_time, 'Preferred Time'
      = @enrollment.preferred_time
    .field
      = f.label :stream_start, 'Stream Start'
      = @enrollment.stream_start
    .field
      = f.label :status
      = @enrollment.status
    .field
      = f.label :date_created, 'Date Created'
      = @enrollment.created_at.strftime '%b %e, %Y @ %r %Z'
    .field
      = f.label :last_updated, 'Last Updated'
      = @enrollment.updated_at.strftime '%b %e, %Y @ %r %Z'

%h2 Notifications
%table.admin-table
  %tr
    %th ID
    %th Enrollment
    %th Message
    %th Start
    %th Status
    %th Delivered At
    %th Actions
  - @notifications.each do |notification|
    %tr{:class => cycle('even', 'odd')}
      %td= notification.id
      %td= notification.enrollment_id
      %td= notification.message_id
      %td= notification.delivery_date.strftime '%Y-%m-%d'
      %td= notification.status
      %td= notification.delivered_at.try(:strftime, '%Y-%m-%d')
      %td.actions #{link_to 'View', [:admin, notification]}